site_name: SeekTHink
site_url: https://walteryangg.github.io/Mkdocs
site_author: Walter
site_description: 积思求索

theme:
  name: material
  #custom_dir: custom_theme/
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.instant
    # - navigation.instant.progress  # 可以先禁用进度条测试
    - content.code.copy
  palette:
    # ----- 亮色模式 -----
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换深色模式

    # ----- 暗色模式 -----
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换亮色模式

    # ----- 自定义主题色 -----
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/palette
        name: 蓝色主题

    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/palette
        name: 绿色主题

    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/palette
        name: 紫色主题

    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/palette
        name: 红色主题
    
    - scheme: default
      primary: grey
      accent: grey
      toggle:
        icon: material/palette
        name: 灰色主题

    - scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/palette
        name: cyan主题
    

plugins:
  - search
  - awesome-pages
  - tags:
  - blog:
      post_dir: blog/posts
      post_url_format: "{date}/{slug}"
      authors_profiles: true
      archive: true

markdown_extensions:
  - attr_list # 可选但推荐，用于支持更丰富的属性
  - md_in_html # 核心：允许混合Markdown与HTML
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
      
extra_css:
  - styles/extra.css
  - styles/homepage.css 

extra_javascript:
  - javascripts/instant-nav-fix.js  # 先加载修复脚本
  - javascripts/homepage.js         # 再加载主页脚本
  
extra:
  generator: false #隐藏页脚网站生成器声明

copyright: Copyright &copy; 2022 - 2025 Walter&积思求索
